Repository fis-g4/learning-microservice, pull requests merged in 2023-12, with the labels that each got.

#18 FEAT: ADD THE FIRST VERSION OF MICROSERVICE OAS
  docs/oas.yaml
Labels: documentation

#16 FEAT: CREATE CLASS ENDPOINTS
  server/index.ts
  server/routes/classes.ts
  server/routes/materials.ts
  server/types.d.ts
Labels: enhancement

#17 FEAT: LINK GOOGLE CLOUD STORAGE DATABASE WITH MATERIAL MODEL
  .gitignore
  README.md
  docker-compose.yml
  server/.env.dev
  server/.env.prod
  server/package-lock.json
  server/package.json
  server/routes/materials.ts
Labels: enhancement

#27 FEAT: LINK GOOGLE CLOUD STORAGE DATABASE WITH CLASS MODEL
  package-lock.json
  package.json
  server/routes/classes.ts
Labels: enhancement

#21 FIX: REVIEW AND CORRECT MATERIAL ENDPOINTS
  docker-compose.yml
  docs/oas.yaml
  server/.env.dev
  server/db/models/material.ts
  server/db/models/user.ts
  server/db/populateInitial.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/routes/materials.ts
  server/routes/users.ts
  server/types.d.ts
  server/utils/errorMessages/jwt.ts
  server/utils/jwtUtils.ts
Labels: bug

#23 TEST: IMPLEMENT MATERIAL TESTS
  .github/workflows/deployment.yml
  .github/workflows/tests.yml
  server/app.ts
  server/babel.config.js
  server/index.ts
  server/jest.config.ts
  server/package-lock.json
  server/package.json
  server/routes/classes.ts
  server/routes/materials.ts
  server/tests/materials.test.ts
  server/utils/jwtUtils.ts
Labels: test

#29 FIX: REVIEW AND CORRECT CLASS ENDPOINTS
  server/app.ts
  server/db/models/class.ts
  server/routes/classes.ts
  server/utils/auth/auth.ts
Labels: bug
