Repository fis-g4/learning-microservice, pull requests merged in 2024-01, with the labels that each got.

#32 FEAT(#026): IMPLEMENT ASYNC OPERATIONS
  docker-compose.yml
  server/.env.dev
  server/db/conn.ts
  server/db/populateInitial.ts
  server/index.ts
  server/package-lock.json
  server/package.json
  server/rabbitmq/operations.ts
  server/routes/classes.ts
  server/routes/materials.ts
Labels: enhancement

#35 FEAT(#034): ADD NECESSARY FILES FOR CD
  .github/workflows/cd.yml
  .github/workflows/deployment.yml
  .github/workflows/tests.yml
  .gitignore
  chart/Chart.yaml
  chart/templates/_helpers.tpl
  chart/templates/deployment.yaml
  chart/templates/mongo-secrets.yaml
  chart/templates/service.yaml
  chart/values.yaml
  chart/workflows/deployment.yml
  docker-compose.yml
  package-lock.json
  package.json
  server/.env.dev
  server/app.ts
  server/package-lock.json
  server/package.json
  server/rabbitmq/operations.ts
  server/routes/classes.ts
  server/routes/materials.ts
  server/tests/materials.test.ts
  terraform/gce.tf
  terraform/group.tf
  terraform/main.tf
  terraform/router.tf
  terraform/variables.tf
Labels: enhancement, deploy

#37 FEAT(#36): IMPLEMENT GET ROUTES
  server/routes/classes.ts
  server/routes/materials.ts
  server/tests/materials.test.ts
Labels: enhancement

#39 CHANGE JWT FUNCTIONS
  .github/workflows/tests.yml
  GoogleCloudKey.gpg
  server/.env.dev
  server/.env.prod
  server/app.ts
  server/package-lock.json
  server/package.json
  server/routes/materials.ts
  server/tests/materials.test.ts
  server/utils/auth/auth.ts
  server/utils/jwtUtils.ts
Labels: bug, test

#46 FEAT/FIX(#042): REVIEW ASYNC OPERATIONS AND IMPLEMENT MATERIALIZED VIEW PATTERN
  server/db/models/class.ts
  server/db/models/material.ts
  server/db/models/materializedUsers.ts
  server/db/populateInitial.ts
  server/rabbitmq/operations.ts
  server/routes/classes.ts
  server/routes/materials.ts
  server/tests/materials.test.ts
Labels: bug, enhancement

#44 IMPLEMENT FEATURE TOGGLE LIMIT UPLOAD SIZE
  server/.env.dev
  server/.env.prod
  server/routes/classes.ts
  server/routes/materials.ts
  server/tests/materials.test.ts
Labels: enhancement

#30 TEST(#25): ADD TEST TO CLASS ENDPOINTS
  server/.env.dev
  server/.env.prod
  server/db/models/class.ts
  server/routes/classes.ts
  server/tests/classes.test.ts
  server/types.d.ts
Labels: test

#48 FEAT(#47): ADD VERIFICATIONS AND MOCK COURSE ON CLASS ENDPOINTS
  server/routes/classes.ts
  server/tests/classes.test.ts
Labels: enhancement
